/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "surface-container-high": "#141f38",
                "primary-fixed": "#00f4fe",
                "on-secondary-fixed-variant": "#006544",
                "secondary-container": "#006c49",
                "surface": "#060e20",
                "surface-dim": "#060e20",
                "tertiary-fixed-dim": "#49a8fc",
                "background": "#060e20",
                "surface-container-highest": "#192540",
                "on-error": "#490006",
                "secondary": "#69f6b8",
                "on-secondary-fixed": "#00452d",
                "on-error-container": "#ffa8a3",
                "surface-container-low": "#091328",
                "on-primary-container": "#00575b",
                "surface-variant": "#192540",
                "outline": "#6d758c",
                "surface-tint": "#a1faff",
                "outline-variant": "#40485d",
                "inverse-surface": "#faf8ff",
                "on-primary": "#006165",
                "secondary-fixed-dim": "#58e7ab",
                "secondary-fixed": "#69f6b8",
                "surface-container-lowest": "#000000",
                "on-tertiary": "#003053",
                "on-tertiary-fixed": "#00192f",
                "surface-container": "#0f1930",
                "tertiary": "#64b3ff",
                "on-tertiary-container": "#002440",
                "tertiary-container": "#45a6fa",
                "tertiary-dim": "#41a3f7",
                "on-surface-variant": "#a3aac4",
                "primary-container": "#00f4fe",
                "inverse-on-surface": "#4d556b",
                "inverse-primary": "#006a6e",
                "on-surface": "#dee5ff",
                "surface-bright": "#1f2b49",
                "on-secondary": "#005a3c",
                "primary": "#a1faff",
                "error-dim": "#d7383b",
                "on-secondary-container": "#e1ffec",
                "tertiary-fixed": "#6bb6ff",
                "primary-fixed-dim": "#00e5ee",
                "primary-dim": "#00e5ee",
                "error": "#ff716c",
                "on-tertiary-fixed-variant": "#003c65",
                "on-primary-fixed-variant": "#006266",
                "on-background": "#dee5ff",
                "error-container": "#9f0519",
                "secondary-dim": "#58e7ab",
                "on-primary-fixed": "#004346",
            },
            fontFamily: {
                headline: ["Space Grotesk", "sans-serif"],
                body: ["Manrope", "sans-serif"],
                label: ["Manrope", "sans-serif"],
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
        },
    },
    plugins: [],
};
